[[main]]
  name = "Home"
  url = ""
  weight = 1

[[main]]
  name = "Technology"
  url = "tech/"
  weight = 10

[[main]]
  parent = "Technology"
  name = "Security"
  url = "tech/security/"
  weight = 20

[[main]]
  parent = "Technology"
  name = "Cloud"
  url = "tech/cloud/"
  weight = 30

[[main]]
  name = "Journey"
  url = "journey/"
  weight = 40

[[main]]
  name = "Opinion"
  url = "opinion/"
  weight = 50

[[main]]
  name = "Tutorial"
  url = "https://tutorial.muismu.com"
  weight = 60

[[main]]
  name = "Awesome"
  url = "awesome/"
  weight = 70

[[main]]
  name = "About"
  url = "about/"
  weight = 100

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 200
  url = "https://github.com/agoodmu"

#[[social]]
#  name = "linkedin"
#  weight = 3
#  url = "https://www.linkedin.com/in/#"

[[social]]
  name = "rss"
  weight = 61
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
# name = "bluesky"
# url = "https://bsky.app/profile/#"