[[main]]
  name = "Home"
  url = ""
  weight = 1

[[main]]
  name = "Technology"
  url = "post/travel/"
  weight = 10

[[main]]
  parent = "Technology"
  name = "Security"
  url = "post/security/"
  weight = 20

[[main]]
  parent = "Technology"
  name = "Cloud"
  url = "post/cloud/"
  weight = 30

[[main]]
  name = "Travel"
  url = "post/travel/"
  weight = 40

[[main]]
  name = "Immigration"
  url = "post/immigration/"
  weight = 40

[[main]]
  name = "About"
  url = "about/"
  weight = 50

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 60
  url = "https://github.com/agoodmu"

#[[social]]
#  name = "linkedin"
#  weight = 3
#  url = "https://www.linkedin.com/in/#"

[[social]]
  name = "rss"
  weight = 61
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
# name = "bluesky"
# url = "https://bsky.app/profile/#"